### ISSUE TITLE
Add some vim learning resources

### ISSUE THREAD

**Issue by arthurvr** [akrawchyk/awesome-vim#10]
Like books, tutorials, ... for beginners. Currently the list is a little too much a list of just plugins. So many more awesome things than plugins out there.

**Comment by akrawchyk** [comment]
This is an excellent idea! I'll add a few resources to the top of the readme for now. Please feel free to open a PR against the repo to add any links or websites you find useful :+1:

**Comment by akrawchyk** [comment]
Added with https://github.com/akrawchyk/awesome-vim/pull/14. Thanks for suggesting this!
