### ISSUE TITLE
Vim/Neovim Start page: vim-startify

### ISSUE THREAD

**Issue by oldgaro** [akrawchyk/awesome-vim#36]
https://github.com/mhinz/vim-startify

**Comment by akrawchyk** [comment]
@oldgaro great suggestion, can you open a PR and add it to the section you think is appropriate? Maybe `Tools > Interface`?

**Comment by akrawchyk** [comment]
https://github.com/akrawchyk/awesome-vim/commit/31d315958556850ff89dcc769c3d919a95781d24
