### ISSUE TITLE
usevim.com is not a site about vim (anymore)

### ISSUE THREAD

**Issue by patrick96** [akrawchyk/awesome-vim#46]
[usevim.com](https://www.usevim.com/), which is listed in the *[Websites](https://github.com/akrawchyk/awesome-vim#websites)* section, seems to be a site totally unrelated to vim. I have no idea what happened to the original site though.

**Comment by akrawchyk** [comment]
You're totally right, weird! Thanks @patrick96 I'll remove.

**Comment by akrawchyk** [comment]
removed in https://github.com/akrawchyk/awesome-vim/commit/85d6bfd1fa37ae268d302bb0529a721197753d7a
