### ISSUE TITLE
Add a `contributing.md` file

### ISSUE THREAD

**Issue by arthurvr** [akrawchyk/awesome-vim#7]
With clear guidelines when and how to contribute.

See https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines

**Comment by akrawchyk** [comment]
Merged in one with https://github.com/akrawchyk/awesome-vim/pull/11. Let me know if you have suggestions for what else should be included in the contribution guidelines. Thanks!
